rabbit_connection:
  host: ${RABBITMQ_HOST:127.0.0.1}
  port: ${RABBITMQ_PORT:5672}
  virtual_host: ${RABBITMQ_VIRTUAL_HOST:arupy}
  ssl: false
  ssl_options:
    certfile: client/cert.pem
    keyfile: client/key.pem
    ca_certs: Null
rabbit_credentials:
  username: ${RABBITMQ_USER:arupy}
  password: ${RABBITMQ_PASS:arupy}
